version: '3.1'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    expose:
      - 27017
    volumes:
      - ./docker/mongo:/bitnami
  website:
    image: 'bitnami/node:8'
    restart: 'always'
    command: "sh -c 'npm run server'"
    ports:
      - '8096:8096'
    environment:
      - DEBUG=${DEBUG}
      - NODE_ENV=${NODE_ENV}
      - LOG_DIR=${LOG_DIR}
      - MONGO_URL=${MONGO_URL}
      - POSTMARK_KEY=${POSTMARK_KEY}
      - PORT=${PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_SIGNATURE_VERSION=${AWS_SIGNATURE_VERSION}
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb